routes/web.php
<?php

Route::redirect('/', '/login');

Route::redirect('/home', '/admin');

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');

    Route::resource('users', 'UsersController');

    Route::POST('students/studentFilter', 'StudentsController@studentFilter')->name('students.filtered');

    Route::resource('students', 'StudentsController');

});

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $dates = [
        'created_at',
        'updated_at'
    ];

    protected $fillable = [
        'group_id',
        'faculty_id',
        'name',
        'surname',
        'email',
        'phone',
        'created_at',
        'updated_at'
    ];

    /**
     * Get the group for the student.
     */

    public function group()
    {
        return $this->belongsTo(Group::Class);
    }

    /**
     * Get the group for the student.
     */
    public function faculty()
    {
        return $this->belongsTo(Faculty::Class);
    }
}

app/Http/Controllers/Admin/StudentsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreStudentRequest;
use App\Http\Requests\UpdateStudentRequest;
use Illuminate\Http\Request;
use App\Group;
use App\Course;
use App\Faculty;
use App\Student;

class StudentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        $faculties = Faculty::all();

        return view('admin.students.index', compact('faculties'));
    }

    public function studentFilter(Request $request)
    {
        $students = Student::with(['faculty', 'group'])->get();

        if(!empty($request->input('faculty'))) {
            $students = Student::where('faculty_id', $request->input('faculty'))->get();
        }

        if(!empty($request->input('course'))) {
            $students = Course::where('course_number', $request->input('course'))->firstOrFail()->students;
        }

        if(!empty($request->input('group'))) {
            $students = Group::where('group_number', $request->input('group'))->firstOrFail()->students;
        }

        $datatable = datatables()->of($students)
            ->editColumn('id', '')
            ->setRowAttr([
                'data-entry-id' => function($student) {
                    return $student->id;
                },
            ])
            ->editColumn('faculty', function ($student) {
                return !empty($student->faculty->name) ? $student->faculty->name : '';
            })
            ->editColumn('course', function ($student) {
                return !empty($student->group->course->course_number) ? $student->group->course->course_number : '';
            })
            ->editColumn('group', function ($student) {
                return !empty($student->group->group_number) ? $student->group->group_number : '';
            })
            ->addColumn('action', function ($student) {
                return '<a href="' . route('admin.students.edit', $student->id) . '" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> Edit</a>';
            })
            ->setRowId('id');


        return $datatable->make(true);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function create()
    {
       $faculties = Faculty::all();
       $courses   = Course::all();
       $groups    = Group::all();

        return view('admin.students.create', compact('faculties', 'courses', 'groups'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    public function store(StoreStudentRequest $request)
    {
        Student::create($request->all());

        return redirect()->route('admin.students.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */

    public function show(Student $student)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */

    public function edit(Student $student)
    {
        $faculties = Faculty::all();
        $courses   = Course::all();
        $groups    = Group::all();

        return view('admin.students.edit', compact('student', 'faculties', 'courses', 'groups'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */

    public function update(UpdateStudentRequest $request, Student $student)
    {
        $student->update($request->all());

        return redirect()->route('admin.students.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */

    public function destroy(Student $student)
    {
        //
    }
}

resources/views/admin/students/create.blade.php
@extends('layouts.admin')
@section('content')

    <div class="card">
        <div class="card-header">
            {{ trans('global.create') }} {{ trans('global.student.title_singular') }}
        </div>

        <div class="card-body">
            <form action="{{ route("admin.students.store") }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                    <label for="name">{{ trans('global.student.fields.name') }}*</label>
                    <input type="text" id="name" name="name" class="form-control" value="{{ old('name', isset($student) ? $student->name : '') }}">
                    @if($errors->has('name'))
                        <em class="invalid-feedback">
                            {{ $errors->first('name') }}
                        </em>
                    @endif
                    <p class="helper-block">
                        {{ trans('global.student.fields.name_helper') }}
                    </p>
                </div>
                <div class="form-group {{ $errors->has('surname') ? 'has-error' : '' }}">
                    <label for="name">{{ trans('global.student.fields.surname') }}*</label>
                    <input type="text" id="surname" name="surname" class="form-control" value="{{ old('name', isset($student) ? $student->surname : '') }}">
                    @if($errors->has('surname'))
                        <em class="invalid-feedback">
                            {{ $errors->first('surname') }}
                        </em>
                    @endif
                    <p class="helper-block">
                        {{ trans('global.student.fields.surname_helper') }}
                    </p>
                </div>
                <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                    <label for="name">{{ trans('global.student.fields.email') }}*</label>
                    <input type="text" id="email" name="email" class="form-control" value="{{ old('email', isset($student) ? $student->email : '') }}">
                    @if($errors->has('email'))
                        <em class="invalid-feedback">
                            {{ $errors->first('email') }}
                        </em>
                    @endif
                    <p class="helper-block">
                        {{ trans('global.student.fields.email_helper') }}
                    </p>
                </div>
                <div class="form-group {{ $errors->has('phone') ? 'has-error' : '' }}">
                    <label for="name">{{ trans('global.student.fields.phone') }}*</label>
                    <input type="text" id="phone" name="phone" class="form-control" value="{{ old('phone', isset($student) ? $student->phone : '') }}">
                    @if($errors->has('phone'))
                        <em class="invalid-feedback">
                            {{ $errors->first('phone') }}
                        </em>
                    @endif
                    <p class="helper-block">
                        {{ trans('global.student.fields.phone_helper') }}
                    </p>
                </div>
                <div class="form-group filter_type">
                    <label for="faculty_id">{{ trans('global.student.fields.faculty') }}</label>
                    <select name="faculty_id" id="faculty_id" class="form-control">
{{--                        <option value="" disabled>{{ trans('global.student.fields.faculty') }}</option>--}}
                        @foreach($faculties as $faculty)
                            <option value="{{ $faculty->id }}">{{ $faculty->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group filter_type">
                    <label for="course_id">{{ trans('global.student.fields.course') }}</label>
                    <select name="course_id" id="course_id" class="form-control">
{{--                        <option value="" disabled>{{ trans('global.student.fields.course') }}</option>--}}
                        @foreach($courses as $course)
                            <option value="{{ $course->id }}">{{ $course->course_number }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group filter_type">
                    <label for="group_id">{{ trans('global.student.fields.group') }}</label>
                    <select name="group_id" id="group_id" class="form-control">
                        @foreach($groups as $group)
                            <option value="{{ $group->id }}">{{ $group->group_number }}</option>
                        @endforeach
                    </select>
                </div>
                <div>
                    <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/admin/students/edit.blade.php
@extends('layouts.admin')
@section('content')

    <div class="card">
        <div class="card-header">
            {{ trans('global.edit') }} {{ trans('global.student.title_singular') }}
        </div>

        <div class="card-body">
            <form action="{{ route("admin.students.update", [$student->id]) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                    <label for="name">{{ trans('global.student.fields.name') }}*</label>
                    <input type="text" id="name" name="name" class="form-control" value="{{ old('name', isset($student) ? $student->name : '') }}">
                    @if($errors->has('name'))
                        <em class="invalid-feedback">
                            {{ $errors->first('name') }}
                        </em>
                    @endif
                    <p class="helper-block">
                        {{ trans('global.student.fields.name_helper') }}
                    </p>
                </div>
                <div class="form-group {{ $errors->has('surname') ? 'has-error' : '' }}">
                    <label for="name">{{ trans('global.student.fields.surname') }}*</label>
                    <input type="text" id="surname" name="surname" class="form-control" value="{{ old('name', isset($student) ? $student->surname : '') }}">
                    @if($errors->has('surname'))
                        <em class="invalid-feedback">
                            {{ $errors->first('surname') }}
                        </em>
                    @endif
                    <p class="helper-block">
                        {{ trans('global.student.fields.surname_helper') }}
                    </p>
                </div>
                <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                    <label for="name">{{ trans('global.student.fields.email') }}*</label>
                    <input type="text" id="email" name="email" class="form-control" value="{{ old('email', isset($student) ? $student->email : '') }}">
                    @if($errors->has('email'))
                        <em class="invalid-feedback">
                            {{ $errors->first('email') }}
                        </em>
                    @endif
                    <p class="helper-block">
                        {{ trans('global.student.fields.email_helper') }}
                    </p>
                </div>
                <div class="form-group {{ $errors->has('phone') ? 'has-error' : '' }}">
                    <label for="name">{{ trans('global.student.fields.phone') }}*</label>
                    <input type="text" id="phone" name="phone" class="form-control" value="{{ old('phone', isset($student) ? $student->phone : '') }}">
                    @if($errors->has('phone'))
                        <em class="invalid-feedback">
                            {{ $errors->first('phone') }}
                        </em>
                    @endif
                    <p class="helper-block">
                        {{ trans('global.student.fields.phone_helper') }}
                    </p>
                </div>
                <div class="form-group filter_type">
                    <label for="faculty_id">{{ trans('global.student.fields.faculty') }}</label>
                    <select name="faculty_id" id="faculty_id" class="form-control">
                        {{--                        <option value="" disabled>{{ trans('global.student.fields.faculty') }}</option>--}}
                        @foreach($faculties as $faculty)
                            <option value="{{ $faculty->id }}" <?=$faculty['id'] == $student->faculty_id ? 'selected' : '';?>>{{ $faculty->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group filter_type">
                    <label for="course_id">{{ trans('global.student.fields.course') }}</label>
                    <select name="course_id" id="course_id" class="form-control">
                        {{--                        <option value="" disabled>{{ trans('global.student.fields.course') }}</option>--}}
                        @foreach($courses as $course)
                            <option value="{{ $course->id }}">{{ $course->course_number }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group filter_type">
                    <label for="group_id">{{ trans('global.student.fields.group') }}</label>
                    <select name="group_id" id="group_id" class="form-control">
                        @foreach($groups as $group)
                            <option value="{{ $group->id }}" <?=$group['id'] == $student->group_id ? 'selected' : '';?>>{{ $group->group_number }}</option>
                        @endforeach
                    </select>
                </div>
                <div>
                    <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/admin/students/index.blade.php
@extends('layouts.admin')
@section('content')
        <div style="margin-bottom: 10px;" class="row">
            <div class="col-lg-12">
                <a class="btn btn-success" href="{{ route("admin.students.create") }}">
                    {{ trans('global.add') }} {{ trans('global.student.title_singular') }}
                </a>
            </div>
        </div>
    <div class="card">
        <div class="card-header">
            {{ trans('global.student.title_singular') }} {{ trans('global.list') }}
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <div id="student-datatable-filter" class="panel panel-default">
                    <div class="panel-body">
                        <form method="POST" id="search-form" class="form-inline" role="form">

                            <div class="form-group filter_type">
                                <label for="filter_type">{{ trans('global.datatables.filter_type') }}</label>
                                <select name="filter_type" id="filter_type" class="form-control">
                                    <option value="">{{ trans('global.datatables.filter_type') }}</option>
                                    <option value="faculty">{{ trans('global.student.fields.faculty') }}</option>
                                    <option value="course">{{ trans('global.student.fields.course') }}</option>
                                    <option value="group">{{ trans('global.student.fields.group') }}</option>
                                </select>
                            </div>

                            <div class="form-group" id="filter-faculty-section">
                                <label for="faculty_filter">{{ trans('global.datatables.faculty') }}</label>
                                <select name="faculty_filter" id="faculty_filter" class="form-control">
                                    <option value="">{{ trans('global.student.fields.faculty') }}</option>
                                    @foreach($faculties as $faculty)
                                        <option value="{{ $faculty->id }}">{{ $faculty->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group" id="filter-course-section">
                                <label for="course_filter">{{ trans('global.datatables.course') }}</label>
                                <input type="text" class="form-control" name="course" id="course_filter" placeholder="{{ trans('global.datatables.course_search') }}">
                            </div>
                            <div class="form-group" id="filter-group-section">
                                <label for="group_filter">{{ trans('global.datatables.group') }}</label>
                                <input type="text" class="form-control" name="group" id="group_filter" placeholder="{{ trans('global.datatables.group_search') }}">
                            </div>
                            <div id="submit-filter" class="form-group">
                                <button type="submit" class="btn btn-primary">Search</button>
                            </div>
                        </form>
                    </div>
                </div>
                <table id="student-datatable" class=" table table-bordered table-striped table-hover datatable">
                    <thead>
                    <tr>
                        <th>

                        </th>
                        <th>
                            {{ trans('global.student.fields.name') }}
                        </th>
                        <th>
                            {{ trans('global.student.fields.surname') }}
                        </th>
                        <th>
                            {{ trans('global.student.fields.email') }}
                        </th>
                        <th>
                            {{ trans('global.student.fields.phone') }}
                        </th>
                        <th>
                            {{ trans('global.student.fields.faculty') }}
                        </th>
                        <th>
                            {{ trans('global.student.fields.course') }}
                        </th>
                        <th>
                            {{ trans('global.student.fields.group') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
@section('scripts')
    @parent
    <script>
        $(function () {
           let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)

            $('#student-datatable').DataTable({
                searching: true,
               buttons: dtButtons,
                processing: true,
                serverSide: true,
                ajax: {
                    headers: {'x-csrf-token': _token},
                    type: 'POST',
                    url:"{{ route('admin.students.filtered') }}",
                    data: function (d) {
                        d.faculty = $('#faculty_filter').val();
                        d.course = $('#course_filter').val();
                        d.group = $('#group_filter').val();
                    }
                },
                columns: [
                    { data: 'id', name: 'id', orderable: false, searchable: false, printable: false},
                    { data: 'name', name: 'name' },
                    { data: 'surname', name: 'surname' },
                    { data: 'email', name: 'email' },
                    { data: 'phone', name: 'phone' },
                    { data: 'faculty', name: 'faculty' },
                    { data: 'course', name: 'course' },
                    { data: 'group', name: 'group' },
                    { data: 'action', name: 'action', orderable: false, searchable: false, printable: false },
                ],
                order: [[0, 'desc']]

            });

            $("#search-form").on("submit", function(event) {
                event.preventDefault();

                $('#student-datatable').DataTable().draw(true);
            });

            $("#filter_type").on("change", function() {
                var filter = $(this).val();
                var activeFilter = '#filter-' + filter + '-section';

                $(this).parents('form').find('div').removeClass('active');
                $(this).parents('form').find('div:not(.filter_type) input, div:not(.filter_type) select').val('');

                if(filter !== '') {
                    $(activeFilter).addClass('active');
                    $("#submit-filter").addClass('active');
                } else {
                    $("#submit-filter").removeClass('active');
                    $('#student-datatable').DataTable().draw(true);
                }
            });
        })

    </script>
@endsection
@endsection